// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6l0iQ2vXDXIxSgpyBE24O9m_evcWRYm0',
    appId: '1:734027859448:web:8ef731564152b5c217820d',
    messagingSenderId: '734027859448',
    projectId: 'atharv-738cb',
    authDomain: 'atharv-738cb.firebaseapp.com',
    storageBucket: 'atharv-738cb.appspot.com',
    measurementId: 'G-80C4N35QF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmzzMsaDxuiKNp4MenBR30RIRSC1v2BoY',
    appId: '1:734027859448:android:be0c0ab1d8eaa6f517820d',
    messagingSenderId: '734027859448',
    projectId: 'atharv-738cb',
    storageBucket: 'atharv-738cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAePR7Vo-RrGCdSkGU9YBl14BLTpldbQ5U',
    appId: '1:734027859448:ios:d2380f024537376717820d',
    messagingSenderId: '734027859448',
    projectId: 'atharv-738cb',
    storageBucket: 'atharv-738cb.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAePR7Vo-RrGCdSkGU9YBl14BLTpldbQ5U',
    appId: '1:734027859448:ios:287a63422aa0012b17820d',
    messagingSenderId: '734027859448',
    projectId: 'atharv-738cb',
    storageBucket: 'atharv-738cb.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
